name: build action
on:
  push:
    branches: [ mecab ]
jobs:
  build_web:
    name: 編譯程式
    runs-on: windows-2019
    steps:
      - name: Install msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win32_msvc2019
      - name: 下載必要檔案
        run: |
          ls D:\a\Textractor\Qt\5.15.2\msvc2019\bin\ > folder.txt
      - name: 結果
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: folder.txt
      
      
