name: build action
on:
  push:
    branches: [ mecab ]
jobs:
  build_web:
    name: 編譯程式
    runs-on: windows-2019
    steps:
      - name: 下載必要檔案
        run: |
          Get-ExecutionPolicy
      
      
