name: build action
on:
  push:
    branches: [ mecab ]
jobs:
  build_web:
    name: 編譯程式
    runs-on: windows-2019
    steps:
      - name: Install msvc
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win32_msvc2019
      - name: 下載必要檔案
        run: |
          cd ~
          Invoke-WebRequest -Uri https://github.com/yashichi05/Mecab_Lib/raw/main/mecab.7z -OutFile m.7z
          Invoke-WebRequest -Uri https://www.7-zip.org/a/7z1900-x64.exe -OutFile 7z.exe
          7z.exe
          $ENV:Path = $ENV:Path + "C:\Program Files\7-Zip;"
          7z x m.7z
      - name: 檢查分支
        uses: actions/checkout@v3
      - name: 初始化 
        run: |
          git submodule update --init
          mv ~/mecab extensions/
          cmake -S ./ -B build -G "Visual Studio 16 2019" -A win32
      - name: 編譯 
        run: |
          msbuild ./build/Textractor.sln /p:Configuration=Release /p:Platform="win32"
      - name: 複製 
        run: |
          $ErrorActionPreference = "Continue"
          ./deploy_mecab.ps1
      - name: 結果
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: Textractor
      
      
