name: build action
on:
  push:
    branches: [ mecab ]
jobs:
  build_web:
    name: 編譯程式
    runs-on: windows-2019
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win64_msvc2019_64
      - name: 下載mecab
        run: ls

